#!/usr/bin/env python3
##
## EPITECH PROJECT, 2018
## 101pong
## File description:
## return coordinate, angle, velocity of a pong ball
##

import sys
import math

if len(sys.argv) != 8:
        sys.exit(84)

if len(sys.argv) == 8:
    print("The velocity vector of the ball is:")
    x = float(float(sys.argv[4]) - float(sys.argv[1]));
    y = float(float(sys.argv[5]) - float(sys.argv[2]));
    z = float(float(sys.argv[6]) - float(sys.argv[3]));
    n = int(int(sys.argv[7]))
    print("({0:.2f}, {1:.2f}, {2:.2f})".format(x, y, z))
    print("At time t + {0:d}, ball coordinates will be:".format(n))
    x1 = float(float(x) * int(sys.argv[7]) + float(sys.argv[4]))
    y1 = float(float(y) * int(sys.argv[7]) + float(sys.argv[5]))
    z1 = float(float(z) * int(sys.argv[7]) + float(sys.argv[6]))
    print("({0:.2f}, {1:.2f}, {2:.2f})".format(x1, y1, z1))
    if float(sys.argv[6]) > float(sys.argv[3]) and float(sys.argv[6]) < 0 and z1 > 0 or float(sys.argv[6]) < float(sys.argv[3]) and float(sys.argv[6]) > 0 and z1 < 0:
        print("The incidence angle is:")
        x2 = float(x1 - float(sys.argv[1]))
        y2 = float(y1 - float(sys.argv[2]))
        z2 = float(z1 - float(sys.argv[3]))
        lenght_u = float(math.sqrt(pow(z2, 2)))
        lenght_v = float(math.sqrt(pow(x2, 2) + pow(y2, 2) + pow (z2, 2)))
        mul_lenght = float(lenght_u * lenght_v)
        result = float(pow(z2, 2) / mul_lenght)
        final_result = 90 - float(math.acos(result)) * 180 / math.pi
        print("{0:.2f} degrees".format(final_result))
    elif z == 0 and x == 0 and y != 0 or z == 0 and x != 0 and y == 0:
        print("The incidence angle is:\n0.00 degrees")
    else:
        print("The ball won't reach the bat.")
          
